### ISSUE TITLE
String Comparison Unit Test Failing on Linux

### ISSUE THREAD

**Issue by brwarner** [brwarner/inkcpp#18]
```
1: Scenario: compare concatenated values
1:       Given: string and numbers
1:        When: concatenated string representation match (many fields)
1:        Then: == results true
1: -------------------------------------------------------------------------------
1: /home/runner/work/inkcpp/inkcpp/inkcpp_test/Value.cpp:82
1: ...............................................................................
1: 
1: /home/runner/work/inkcpp/inkcpp/inkcpp_test/Value.cpp:85: FAILED:
1:   REQUIRE( res.get<int32_t>() == 1 )
1: with expansion:
1:   0 == 1
```

Full Log: https://github.com/brwarner/inkcpp/runs/1881136054?check_suite_focus=true

**Comment by brwarner** [comment]
Strange that it only fails on Linux and not Win/Mac...

**Comment by JBenda** [comment]
Interesting, on my Linux is dose't fail ...
![image](https://user-images.githubusercontent.com/7237254/107680101-b78bf480-6c9d-11eb-8058-df2a647d125c.png)

**Comment by brwarner** [comment]
Maybe try a release build locally? That's what the GitHub action is using.

**Comment by JBenda** [comment]
Yes, now it fails too localy, Ok than I can start debugging ^^

**Comment by brwarner** [comment]
Cool. If you merge master before uploading your PR, it should now automatically run the tests on the PR.
