### ISSUE TITLE
inkcpp_test does not compile on M1 / arm64

### ISSUE THREAD

**Issue by weaversam8** [brwarner/inkcpp#36]
While attempting to use this project with [inkcpp-python](https://github.com/smwhr/inkcpp-python), I followed the instructions listed in the README to build the project. Each of the subprojects builds successfully with the exception of `inkcpp_test`, which reports an invalid opcode in inline assembly:

```
[ 77%] Building CXX object inkcpp_test/CMakeFiles/inkcpp_test.dir/Main.cpp.o
In file included from /Users/username/Git/inkcpp/inkcpp_test/Main.cpp:2:
/Users/username/Git/inkcpp/inkcpp_test/catch.hpp:7937:13: error: unrecognized instruction mnemonic, did you mean: bit, cnt, hint, ins, not?
            CATCH_BREAK_INTO_DEBUGGER();
            ^
/Users/username/Git/inkcpp/inkcpp_test/catch.hpp:7651:79: note: expanded from macro 'CATCH_BREAK_INTO_DEBUGGER'
    #define CATCH_BREAK_INTO_DEBUGGER() []{ if( Catch::isDebuggerActive() ) { CATCH_TRAP(); } }()
                                                                              ^
/Users/username/Git/inkcpp/inkcpp_test/catch.hpp:7630:34: note: expanded from macro 'CATCH_TRAP'
    #define CATCH_TRAP() __asm__("int $3\n" : : ) /* NOLINT */
                                 ^
<inline asm>:1:2: note: instantiated into assembly here
        int $3
        ^
1 error generated.
make[2]: *** [inkcpp_test/CMakeFiles/inkcpp_test.dir/Main.cpp.o] Error 1
make[1]: *** [inkcpp_test/CMakeFiles/inkcpp_test.dir/all] Error 2
make: *** [all] Error 2
```

This is an issue with [Catch](https://github.com/catchorg/Catch2/), and was fixed in this commit: https://github.com/catchorg/Catch2/commit/a25c1a24af8bffd35727a888a307ff0280cf9387 (released as [v3.0.0-preview3](https://github.com/catchorg/Catch2/releases/tag/v3.0.0-preview3).)

**Comment by weaversam8** [comment]
Actually, it looks like this was fixed in this commit: https://github.com/catchorg/Catch2/commit/bad3c930493d08dd7cca2af57cf355d9b7cddb21 and released in the v2.x track as [v2.12.4](https://github.com/catchorg/Catch2/releases/tag/v2.12.4), which should be an easier upgrade than to the v3.x track.

**Comment by JBenda** [comment]
Thanks for the research, I will take a look

**Comment by JBenda** [comment]
Can you try to compile #37, it's contains the v2.12.4.

**Comment by weaversam8** [comment]
Yep, #37 fixes the issue!

**Comment by JBenda** [comment]
Thank you for the input
