### ISSUE TITLE
Test fails on Debug configuration

### ISSUE THREAD

**Issue by LilithSilver** [brwarner/inkcpp#41]
When `ctest -c Debug` is run after the project is built with `cmake --build . --config Debug` , I get the following error:

![image](https://user-images.githubusercontent.com/84940819/171535647-2ee8525c-1c48-4065-9f62-84358fac8dd9.png)

> Program: inkcpp_test.exe
> File: include\xstring
> Line: 1942
> Expression: cannot dereference string iterator because it is out of range (e.g. an end iterator).

I'd look further into it, but I can't seem to figure out how to run tests from Visual Studio and step through the code.

Note that the tests work fine under the Release configuration.

**Comment by JBenda** [comment]
Interesting, I can't remember having the same problem with UNIX ...
If you have time to spare consider looking deeper :)

**Comment by LilithSilver** [comment]
I could; I just can't seem to get the test suite running in VS on Windows (or anything else that would let me debug). I can get it to build and run as part of the build through VS, but I can't get it debugging. Do you know how?

**Comment by JBenda** [comment]
May take a look at #42,  this  should resolve the problem.
Thank you for point us to that. It's a more clean now. Please let me know if it also works for you.

To debug inkcpp_test in VS you start the `inkcpp.sln` project, then right-click on the `inkcpp_test` subproject and selecting it as `set as start project`. Then you can run it with Debugger attached with the green arrow at the top. Hope that helps

**Comment by LilithSilver** [comment]
> May take a look at #42, this should resolve the problem. Thank you for point us to that. It's a more clean now. Please let me know if it also works for you.
> 
> To debug inkcpp_test in VS you start the `inkcpp.sln` project, then right-click on the `inkcpp_test` subproject and selecting it as `set as start project`. Then you can run it with Debugger attached with the green arrow at the top. Hope that helps

Works for me! Also the `set as startup project` is what I was missing; it works now.

Thank you!
