### ISSUE TITLE
Code is not complilable

### ISSUE THREAD

**Issue by Nordsoft91** [brwarner/inkcpp#5]
Looks like code was tested only under Win environment (MSVS)

Compiling with AppleClang 9.1.0 shows multiple compile-time errors.

Please, build target under *NIX environment

**Comment by brwarner** [comment]
Hey Nordsoft,

Thanks for reporting this. I'll give it a shot on Linux when I next put some time into this. 

Just to check, are you compiling with C++17 features enabled on your compiler? I setup CMake to enable it but I'm not sure it works on all environments.

**Comment by 2shady4u** [comment]
@brwarner Just tested out Github Actions for Windows, Linux and MacOS.

https://github.com/2shady4u/inkcpp/actions

Seems there's still some work to make the code truly platform-agnostic.

**Comment by Nordsoft91** [comment]
@brwarner, yes, C++17 used. Quick review has shown:
 - There are some platform-specific functions you use, e.g. _itoa_s.
 - Template specialization should be out of class definition
 - std::exception doesn't receive std::string in ctor, better to use std::runtime_error or std::logic_error (or create own expectation inherits std::exception)

**Comment by brwarner** [comment]
Thanks. I'm part way there in the new `platform` branch. There's some sticky template shenanigans that I'm having trouble parsing but I'll take a look at them next time.

**Comment by brwarner** [comment]
With some help from JBrenda this should now compile on Linux. There may be other issues, which I'll try to look into.
