### ISSUE TITLE
inklecate location

### ISSUE THREAD

**Issue by dustinchen93** [brwarner/inkcpp#54]
I noticed that there is an "inklecate" tool mentioned on the Wiki, which is used for converting .ink files to .json files. However, I couldn't find inklecate in this particular project, and it took me some time to figure it out. Inklecate is actually part of the Inky project, and you can download the released version from this link: https://github.com/inkle/inky/releases. In my case, I found it located in the inky/resources/app.asar.unpacked/main-process/ink directory. I believe there may be others who encounter the same issue, so I decided to share my solution.

**Comment by JBenda** [comment]
Thank you for the Tip. We could probably link the release page of ink in the readme. We also should mention that cmake is also able to fetch inklecate. The Unreal PR has a lot of convincing features which will be merged soon (tm).
